name: secap
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - appdirs=1.4.4=pyhd3eb1b0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=openblas
  - boltons=23.0.0=py310h06a4308_0
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda=23.3.1=py310h06a4308_0
  - conda-content-trust=0.1.3=py310h06a4308_0
  - conda-package-handling=2.0.2=py310h06a4308_0
  - conda-package-streaming=0.7.0=py310h06a4308_0
  - cryptography=38.0.4=py310h9ce1e76_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - ipython=8.10.0=py310h06a4308_0
  - jedi=0.18.1=py310h06a4308_1
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libopenblas=0.3.21=h043d6bf_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mkl=2023.0.0=h6d00ec8_25399
  - mkl-include=2023.0.0=h06a4308_25399
  - ncurses=6.4=h6a678d5_0
  - ninja-base=1.10.2=hd09550d_5
  - numpy=1.23.5=py310hac523dd_0
  - numpy-base=1.23.5=py310h375b286_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=23.0=py310h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=22.3.1=py310h06a4308_0
  - pluggy=1.0.0=py310h06a4308_1
  - pooch=1.4.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.36=py310h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycosat=0.6.4=py310h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.9=h7a1cb2a_2
  - pyyaml=6.0=py310h5eee18b_1
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py310h06a4308_0
  - ruamel.yaml=0.17.21=py310h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py310h5eee18b_1
  - scipy=1.10.0=py310heeff2f4_1
  - setuptools=65.6.3=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py310h06a4308_0
  - tqdm=4.64.1=py310h06a4308_0
  - traitlets=5.7.1=py310h06a4308_0
  - typing=3.10.0.0=py310h06a4308_0
  - urllib3=1.26.14=py310h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.18.0=py310h5eee18b_0
  - pip:
      - absl-py==1.4.0
      - accelerate==0.19.0
      - accelerator==2023.3.10.dev1
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - alfred-py==3.0.7
      - anyio==3.6.2
      - arrow==1.2.3
      - async-timeout==4.0.2
      - attrs==23.1.0
      - audioread==3.0.0
      - beautifulsoup4==4.12.2
      - blessed==1.20.0
      - bottle==0.12.25
      - cachetools==5.3.0
      - click==8.1.3
      - cmake==3.26.1
      - contourpy==1.1.0
      - coverage==7.2.5
      - croniter==1.3.14
      - cycler==0.11.0
      - cython==0.29.34
      - darr==0.5.4
      - dateutils==0.6.12
      - deepdiff==6.3.0
      - deepspeed==0.8.3
      - deprecated==1.2.13
      - diffusers==0.16.1
      - exceptiongroup==1.1.1
      - fastapi==0.88.0
      - filelock==3.10.7
      - fonttools==4.41.0
      - frozenlist==1.3.3
      - fsspec==2023.5.0
      - ftfy==6.1.1
      - funcy==2.0
      - future==0.18.3
      - gensim==4.3.1
      - google-auth==2.18.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.54.2
      - gtrending==0.4.0
      - h11==0.14.0
      - hjson==3.1.0
      - huggingface-hub==0.13.3
      - importlib-metadata==6.1.0
      - iniconfig==2.0.0
      - inquirer==3.1.3
      - itsdangerous==2.1.2
      - jieba==0.42.1
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsons==1.6.3
      - kiwisolver==1.4.4
      - lark==1.1.5
      - lazy-loader==0.2
      - levenshtein==0.21.0
      - librosa==0.10.0.post2
      - lightning==2.0.2
      - lightning-cloud==0.5.36
      - lightning-utilities==0.8.0
      - lit==16.0.0
      - llvmlite==0.40.0
      - loguru==0.7.0
      - markdown==3.4.3
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - matplotlib==3.7.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.0.5
      - multidict==6.0.4
      - natsort==8.3.1
      - netifaces==0.11.0
      - networkx==3.0
      - ninja==1.11.1
      - nltk==3.8.1
      - numba==0.57.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - opencv-python==4.7.0.72
      - opentracing==2.4.0
      - ordered-set==4.1.0
      - pandas==2.0.1
      - pascal-voc-writer==0.1.4
      - pillow==9.5.0
      - portalocker==2.7.0
      - protobuf==4.23.0
      - psutil==5.9.4
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==1.10.7
      - pygments==2.15.1
      - pyjwt==2.7.0
      - pyparsing==3.0.9
      - pyquaternion==0.9.9
      - pytest==7.3.1
      - pytest-asyncio==0.21.0
      - pytest-cov==4.0.0
      - pytest-mock==3.10.0
      - python-dateutil==2.8.2
      - python-editor==1.0.4
      - python-levenshtein==0.21.0
      - python-multipart==0.0.6
      - pytorch-lightning==2.0.2
      - pytz==2023.3
      - rapidfuzz==3.0.0
      - readchar==4.0.5
      - regex==2023.3.23
      - requests-oauthlib==1.3.1
      - rich==13.3.5
      - rsa==4.9
      - scikit-learn==1.2.2
      - sentencepiece==0.1.99
      - setproctitle==1.3.2
      - smart-open==6.3.0
      - sniffio==1.3.0
      - soundfile==0.12.1
      - soupsieve==2.4.1
      - soxr==0.3.5
      - starlette==0.22.0
      - starsessions==1.3.0
      - sympy==1.11.1
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.0
      - threadpoolctl==3.1.0
      - timm==0.6.13
      - tokenizers==0.13.2
      - tomli==2.0.1
      - torch==2.0.0
      - torchaudio==2.0.1
      - torchlibrosa==0.1.0
      - torchmetrics==0.11.4
      - torchvision==0.15.1
      - transformers==4.29.0
      - triton==2.0.0
      - typing-extensions==4.5.0
      - typish==1.9.3
      - tzdata==2023.3
      - uvicorn==0.22.0
      - uvloop==0.17.0
      - waitress==2.1.2
      - websocket-client==1.5.1
      - websockets==11.0.3
      - werkzeug==2.3.4
      - wrapt==1.15.0
      - xdg==6.0.0
      - yarl==1.9.2
      - zipp==3.15.0
prefix: /opt/conda
